import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://checea.edmcs.cn/cloudoa/login")
    page.get_by_placeholder("请输入用户名").click()
    page.get_by_placeholder("请输入用户名").press("CapsLock")
    page.get_by_placeholder("请输入用户名").fill("ydtchen")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("Lz156970.")
    page.get_by_role("textbox", name="验证码").click()
    page.get_by_role("textbox", name="验证码").press("CapsLock")
    page.get_by_role("textbox", name="验证码").fill("")
    page.get_by_role("textbox", name="验证码").press("CapsLock")
    page.get_by_role("textbox", name="验证码").fill("e3hh")
    page.get_by_role("button", name="登 录").click()
    page.get_by_title("邮件管理").click()
    page.get_by_text("公共邮箱").click()
    page.locator("iframe").content_frame.get_by_placeholder("主题").click()
    page.locator("iframe").content_frame.get_by_placeholder("主题").fill("Malindi Wharf")
    page.locator("iframe").content_frame.get_by_role("button", name="搜索").click()
    page.locator("iframe").content_frame.get_by_role("combobox").select_option("90")
    page.locator("iframe").content_frame.locator(".layui-table-fixed > .layui-table-body > .layui-table > tbody > .layui-table-hover > .layui-table-col-special > .layui-table-cell > .layui-unselect > .layui-icon").click()
    page.locator("iframe").content_frame.get_by_role("link", name="Malindi Wharf Project _ Agenda for the Weekly Site Progress Meeting No. 37").click(button="right")
    page.locator("iframe").content_frame.get_by_text("转收文", exact=True).click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("div").filter(has_text=re.compile(r"^请选择信函$")).get_by_placeholder("请选择").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("dd").filter(has_text=re.compile(r"^信函$")).click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("#destinationrad").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("#destinationrad").fill("MLD-PM-CHEC-MoM037")
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.get_by_role("textbox", name="请选择", exact=True).nth(1).click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.get_by_text("Inter-Consult").nth(1).click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("div").filter(has_text=re.compile(r"^请选择E-MAIL纸质信函$")).get_by_placeholder("请选择").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("dd").filter(has_text="E-MAIL").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.get_by_placeholder("请选择项目名称").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.locator("dd").filter(has_text="坦桑尼亚达港马林迪泊位改扩建工程项目").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.get_by_text("").click()
    page.locator("iframe[name=\"layui-layer-iframe1\"]").content_frame.get_by_role("button", name="保 存").click()
    page.get_by_title("文档管理").click()
    page.get_by_text("待发文档").click()
    page.locator("iframe").content_frame.get_by_role("row", name=" 收文 信函 Malindi Wharf Project").locator("i").click()
    page.locator("iframe").content_frame.get_by_role("button", name="流程").click()
    page.locator("iframe").content_frame.get_by_placeholder("请选择").click()
    page.locator("iframe").content_frame.locator("dd").filter(has_text="收文流程").click()
    page.locator("iframe").content_frame.get_by_text("dcc").click()
    page.locator("iframe").content_frame.get_by_placeholder("请选择dcc节点操作人").click()
    page.locator("iframe[name=\"layui-layer-iframe3\"]").content_frame.get_by_text("陈乙东庭（Chen Yidongting）").click()
    page.get_by_text("确定").click()
    page.locator("iframe").content_frame.get_by_role("button", name="启动流程").click()
    page.get_by_title("首页").click()
    page.locator("iframe").content_frame.get_by_role("link", name="[收文流程] Malindi Wharf Project").click()
    page.locator("iframe[name=\"layui-layer-iframe6\"]").content_frame.get_by_role("button", name="提交").click()
    page.locator("iframe[name=\"layui-layer-iframe7\"]").content_frame.get_by_role("button", name="确 定").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
